apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinventory
  labels:
    app: bookinventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinventory
  template:
    metadata:
      labels:
        app: bookinventory
    spec:
      containers:
        - name: bookinventory
          image: jwkimacr.azurecr.io/bookinventory:latest
          ports:
            - containerPort: 8080
          resources:
           limits:
             cpu: 500m
           requests:
             cpu: 200m
